/** Copy F29 — ids espelham docs/F29-monitor-de-execucao/copy.md */

export const GRAPH_COPY = {
  tab: 'Grafo',
  loading: 'Carregando grafo…',
  emptyNoThread: 'Selecione uma thread para ver a execução.',
  emptyIdle: 'Ainda não há delegações nesta thread.',
  nodeRoot: 'Agente',
  nodeBatch: 'Batch',
  nodeStage: 'Stage',
  status: {
    running: 'em execução',
    completed: 'concluído',
    error: 'erro',
    timeout: 'timeout',
    idle: 'ocioso',
    waiting_user: 'aguardando',
    cancelled: 'cancelado',
    pending: 'pendente',
    failed: 'falhou',
    skipped: 'ignorado',
  } as const,
  metaTools: (n: number) => `${n} tools`,
  metaActions: (n: number) => `${n} ações`,
  inspectorTitle: 'Mensagem',
  inspectorFrom: 'De',
  inspectorTo: 'Para',
  inspectorStatus: 'Status',
  inspectorStarted: 'Início',
  inspectorDuration: 'Duração',
  inspectorTask: 'Task',
  inspectorReturn: 'Retorno',
  inspectorClose: 'Fechar',
  inspectorEmptyReturn: '(sem retorno ainda)',
} as const
