// Fonte de verdade: docs/F07-subagents/copy.md. Ids literais (não reinventar texto).
// Bloco "Fora do Escopo Central" do catálogo não é importado aqui.
export const SUBAGENTS_COPY = {
  'subagents.title': 'SubAgents',
  'subagents.subtitle':
    'Definições globais reutilizáveis. Vincule-as a um projeto na tela principal para o agente principal poder invocá-las.',
  'subagents.cta.new': '+ Novo Agente',
  'subagents.search.placeholder': 'Buscar por nome ou descrição…',
  'subagents.filter.model.all': 'Todos os modelos',
  'subagents.tab.all': 'Todos',
  'subagents.empty.none': 'Nenhum subagent ainda. Crie o primeiro com “+ Novo Agente”.',
  'subagents.empty.filtered': 'Nenhum subagent corresponde aos filtros.',
  'subagents.card.badge.disabled': 'desativado',
  'subagents.card.model.inherit': 'herda do pai',
  'subagents.card.model.default': 'default do provider',
  'subagents.card.tools.all': 'todas as tools',
  'subagents.card.tools.none': 'sem tools (read-only)',
  'subagents.card.meta.reasoning': 'Reasoning: {level}',
  'subagents.card.meta.reasoning.inherit': 'herda do pai',
  'subagents.card.meta.reasoning.default': 'default',
  'subagents.card.action.enable': 'Ativar',
  'subagents.card.action.disable': 'Desativar',
  'subagents.card.action.edit': 'Editar',
  'subagents.card.action.delete': 'Excluir',
  'subagents.card.action.delete.confirm': 'Excluir?',
  'subagents.card.action.delete.cancel': 'Não',
  'subagents.error.load': 'Não foi possível carregar os subagents.',
  'subagents.error.delete': 'Não foi possível excluir o subagent.',
  'subagents.error.update': 'Não foi possível atualizar o subagent.',
  'subagents.provider.claude': 'Claude',
  'subagents.provider.codex': 'Codex',
  'subagents.provider.kimi': 'Kimi',
  'subagents.provider.inherit': 'Herda',

  'subagentsForm.title.new': 'Novo subagent',
  'subagentsForm.title.edit': 'Editar subagent',
  'subagentsForm.label.name': 'Nome',
  'subagentsForm.hint.name': 'Chave de invocação, única global.',
  'subagentsForm.placeholder.name': 'ex.: revisor-seguranca',
  'subagentsForm.label.description': 'Descrição',
  'subagentsForm.hint.description': 'O “quando usar” — roteia o agente principal.',
  'subagentsForm.placeholder.description': 'Use para revisar diffs em busca de vulnerabilidades.',
  'subagentsForm.label.category': 'Categoria',
  'subagentsForm.hint.category': 'Opcional — agrupa no menu.',
  'subagentsForm.placeholder.category': 'ex.: qualidade',
  'subagentsForm.label.provider': 'Provider',
  'subagentsForm.provider.inherit': 'Herdar configuração do agente pai',
  'subagentsForm.provider.claude': 'Claude',
  'subagentsForm.provider.codex': 'Codex',
  'subagentsForm.provider.kimi': 'Kimi',
  'subagentsForm.hint.inherit': 'O subagent usará o mesmo provider, modelo e reasoning do agente pai.',
  'subagentsForm.label.model': 'Modelo',
  'subagentsForm.hint.model': 'Padrão do provider quando não escolhido.',
  'subagentsForm.option.model.default': 'Padrão do provider',
  'subagentsForm.label.reasoning': 'Reasoning',
  'subagentsForm.hint.reasoning': 'Níveis suportados pelo modelo escolhido.',
  'subagentsForm.option.reasoning.default': 'Padrão do provider',
  'subagentsForm.reasoning.low': 'Low',
  'subagentsForm.reasoning.medium': 'Medium',
  'subagentsForm.reasoning.high': 'High',
  'subagentsForm.reasoning.extra-high': 'Extra High',
  'subagentsForm.reasoning.max': 'Max',
  'subagentsForm.label.tools': 'Tools',
  'subagentsForm.hint.tools.unrestricted': 'Estado atual: sem restrição (todas as built-ins do provider).',
  'subagentsForm.hint.tools.none': 'Estado atual: nenhuma built-in liberada.',
  'subagentsForm.hint.tools.allowlist': 'Estado atual: somente as tools selecionadas.',
  'subagentsForm.tools.readonly': 'Read-only (Read/Grep/Glob)',
  'subagentsForm.tools.none': 'Nenhuma',
  'subagentsForm.tools.unrestricted': 'Sem restrição',
  'subagentsForm.label.prompt': 'System prompt',
  'subagentsForm.placeholder.prompt': 'Instruções do subagent (system prompt aplicado ao filho).',
  'subagentsForm.label.idleTimeout': 'Timeout de inatividade (min)',
  'subagentsForm.placeholder.idleTimeout': '20 (default)',
  'subagentsForm.hint.idleTimeout':
    'Silêncio total do subagent por esse período interrompe o run com status timeout e devolve o parcial ao orquestrador. Vazio = 20min.',
  'subagentsForm.toggle.enabled': 'Habilitado (toggle global)',
  'subagentsForm.cta.cancel': 'Cancelar',
  'subagentsForm.cta.create': 'Criar',
  'subagentsForm.cta.save': 'Salvar',
  'subagentsForm.cta.loading': 'Salvando...',
  'subagentsForm.error.network':
    'Não foi possível contatar o servidor local. Verifique se o EngrenaCode está em execução.',
  'subagentsForm.error.generic': 'Não foi possível salvar o subagent. Tente novamente.',
  'subagentsForm.error.nameConflict': 'Já existe um subagent com este nome. Escolha outro.',
  'subagentsForm.error.promptOver': 'Prompt acima de 1 MiB. Reduza o tamanho para salvar.',

  'subagentsLink.title': 'SubAgents deste projeto',
  'subagentsLink.empty': 'Nenhum subagent global. Crie no menu SubAgents.',
  'subagentsLink.empty.filtered': 'Nada corresponde aos filtros.',
  'subagentsLink.toggle': 'Ativo neste projeto',
  'subagentsLink.aria.toggle': 'Ativar {name} neste projeto',
  'subagentsLink.pill.on': 'on',
  'subagentsLink.pill.off': 'off',
  'subagentsLink.pill.title.on': 'Habilitado neste projeto',
  'subagentsLink.pill.title.off': 'Desabilitado neste projeto',
  'subagentsLink.move.up': 'Subir {name}',
  'subagentsLink.move.down': 'Descer {name}',
  'subagentsLink.meta.inherit': 'inherit (configuração do pai)',
  'subagentsLink.error.load': 'Não foi possível carregar os subagents do projeto.',
  'subagentsLink.error.link': 'Não foi possível atualizar o vínculo.',
  'subagentsLink.error.enabled': 'Não foi possível alterar o estado no projeto.',
  'subagentsLink.error.reorder': 'Não foi possível reordenar.',
  'subagentsLink.harness.pill': 'SubAgents',
  'subagentsLink.warn.cap': '{N} subagents vinculados — acima de 10; considere enxugar (não bloqueia).',

  'subagentsRun.activity.title': 'Subagents',
  'subagentsRun.activity.section.active': 'Ativos',
  'subagentsRun.activity.section.done': 'Concluídos · {N}',
  'subagentsRun.activity.empty.active': 'Nenhum subagent ativo.',
  'subagentsRun.activity.empty.done': 'Nenhum run concluído nesta thread.',
  'subagentsRun.activity.empty.none': 'Nenhum run de subagent nesta thread.',
  'subagentsRun.activity.status.running': 'rodando…',
  'subagentsRun.activity.status.completed': 'concluído',
  'subagentsRun.activity.status.cancelled': 'cancelado',
  'subagentsRun.activity.status.timeout': 'timeout',
  'subagentsRun.activity.status.error': 'erro',
  'subagentsRun.activity.run.open': 'Abrir o run para auditoria ({provider} · {model})',
  'subagentsRun.timeline.status.running': 'trabalhando…',
  'subagentsRun.timeline.status.completed': 'concluído',
  'subagentsRun.timeline.status.cancelled': 'cancelado',
  'subagentsRun.timeline.status.error': 'erro',
  'subagentsRun.timeline.status.timeout': 'timeout',
  'subagentsRun.timeline.open': 'Abrir o run do subagent (auditoria)',
  'subagentsRun.audit.aria': 'Run do subagent {name}',
  'subagentsRun.audit.close': 'Fechar',
  'subagentsRun.audit.empty.waiting': 'Aguardando a primeira resposta do subagent…',
  'subagentsRun.audit.empty.done': 'Run sem saída.',
  'subagentsRun.audit.section.activity': 'Atividade · {N} ações',
} as const

export type SubagentsCopyId = keyof typeof SUBAGENTS_COPY

export function t(id: SubagentsCopyId, vars?: Record<string, string | number>): string {
  const raw = SUBAGENTS_COPY[id]
  if (!vars) return raw
  return Object.entries(vars).reduce<string>(
    (acc, [key, value]) => acc.replaceAll(`{${key}}`, String(value)),
    raw
  )
}
